[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "pydantic>=2.10.6",
    "pyjwt>=2.10.1",
    "pymongo>=4.11.1",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.34.0",
]
